# -*- coding: utf-8 -*-
"""Aula_02_Codelab_Exercicios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JbcCVUwE68ByH9lftU2MfRLFe6jxbMrG

# Mini projetos

## #01 - Conversor de moedas

Crie um programa que solicite um um valor em real ao usuário e converta esse valor, para:

- DOLAR,
- EURO,
- LIBRA ESTERLINA,
- DÓLAR CANADENSE,
- PESO ARGENTINO,
- PESO CHILENO.

Para esse exercício você precisará realizar uma pesquisa para saber a cotação de cada moeda em real. Mostrar o resultado no formato $ XXXX.XX
"""

real= float (input("Insira um valor em reais (xx.xx): R$ "))

dolar= real * 5.04
euro=  real * 6.13
libra= real * 7.13
canadense= real * 4.16
argentino= real * 0.053 
chileno= real * 0.0070

print()
print( real ,'são',dolar, 'dólares.')
print( real ,'são',euro, 'euros.')
print( real ,'são',libra, 'libras.')
print( real ,'são',canadense, 'dolares canadenses.')
print( real ,'são',argentino, 'pesos argentinos.')
print( real ,'são',chileno, 'pesos chilenos')

real= float (input("Insira um valor em reais (xx.xx): R$ "))

dolar= real * 5.04
euro=  real * 6.13
libra= real * 7.13
canadense= real * 4.16
argentino= real * 0.053 
chileno= real * 0.0070

print()
print( f'R${(real):.2f} são R$ {(dolar):.2f} dólares.')
print( f'R${(real):.2f} são R$ {(euro):.2f} euros.')
print( f'R${(real):.2f} são R$ {(libra):.2f} libras.')
print( f'R${(real):.2f} são R$ {(canadense):.2f} dolares canadenses.')
print( f'R${(real):.2f} são R$ {(argentino):.2f} pesos argentinos.')
print( f'R${(real):.2f} são R$ {(chileno):.2f} pesos chilenos.')

"""## #02 - Calculadora de aumento de aluguel

Vamos construir um programa que irá calcular o aumento anual do seu aluguel.

A sua calculadora vai receber o `valor do aluguel` e calcular o aumento baseado no `IGPM de 31%`. A calculadora deve apresentar o aluguel reajustado no formato `R$ XXXX.XX`.
"""

valorAluguel= float (input('Insira o valor do aluguel (xx.xx): R$ '))
igpm= 0.3
valorAumento= valorAluguel * igpm
valorNovo= valorAumento + valorAluguel
print()

print("O valor atural é: R$", valorAluguel)
print("O aumento com base no IGPM é de: R$", valorAumento)
print("O novo valor com aumento é: R$", valorNovo)

valorAluguel= float (input('Insira o valor do aluguel (xx.xx): R$ '))
igpm= 0.3
valorAumento= valorAluguel * igpm
valorNovo= valorAumento + valorAluguel
print()

print(f'O valor atual é R$ {(valorAluguel):.2f}.')
print(f'O aumento com base no IGPM é de R$ {(valorAumento):.2f}.')
print(f'O novo valor com o aumento é R$ {(valorNovo):.2f}.')