# -*- coding: utf-8 -*-
"""Aula_02_Extras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aPfjOl8DMYqI8scPhfSvbGQoIlEZMSC6

# **Comando Print, Variáveis e Input**

## Comando Print

> Print é uma função que imprimi na tela valores:
"""

print('Hello World')

"""## Variável

> Variável é um espaço na memória RAM que guarda algum dado.

> Em Python todas as váriáveis precisam ser inicializadas com um valor:
"""

idade = 23 #Variável idade que recebe o valor 23

print(idade) #Comando print para imprimir na tela o valor da variável idade.

"""Tipos de variáveis:

* str = Valores entre aspas
* int = Número inteiros
* float = Números decimais
* bool = Valores booleanos: True ou False (sempre com a primeira letra maiúscula)

> Para descobrir qual é o tipo de uma variável eu preciso execultar:
"""

idade = 23

print(type(idade)) #função type que identifica o tipo da var e função print para mostrar na tela o tipo

"""F String:

> É uma forma de escrevermos uma string com variáveis concatenadas de forma elegante:
"""

idade = 23

print(f'Sua var idade tem o valor {idade} que é do tipo: {type(idade)}') #Entre chaves coloque valores que não são string

"""Uma forma simples de atribuir o mesmo valor a várias variáveis é:"""

peso = idade = quantidade = 60

print(f'Peso: {peso}, Idade: {idade}, Quantidade: {quantidade}')

"""Você pode atribuir valores diferentes a variáveis diferentes na mesma linha:"""

inteiro, texto, booleano, flutuante = 23, "Olá", True, 23.5

# Para colocar cada item em uma linha é só adicionar um \n entre as informações:
print(f'Inteiro: {inteiro}\nTexto: {texto}\nBooleano: {booleano}\nFlutuante: {flutuante}')

"""## Função Input

> É uma função que solicita ao usuário algum valor, ele sempre transforma o valor inserido em uma string:
"""

idade = input('Quantos anos você tem? ')

print(type(idade))
print(f'Que legal! Você tem {idade} anos')

"""Para mudar o tipo do valor que vai entrar no input você pode utilizar as funções:

* str() - Garante o tipo string
* int() - Altera para o tipo inteiro
* float() - Altera para o tipo float

Podemos utilizar isso para solicitar dois valores e fazer a soma deles por exemplo:
"""

valor1 = int(input('Digite o primeiro valor: '))
valor2 = int(input('Digite os egundo valor: '))
soma = valor1 + valor2

print(f'A soma de {valor1} + {valor2} é = {soma}')

"""## Primeiros Exercícios

01 - Elabore um programa que imprima na tela a seguinte frase `Olá Mundo! Esse é o meu primeiro programa`
"""

print ('Olá Mundo! Esse é o meu primeiro programa')

"""02 - Elabore um programa que escreve seu nome completo na primeira linha, seu endereço na segunda e o CEP e telefone na terceira.  

**Exemplo:**
```
Nome: Bruno Fabri
Endereço: Rua ABC
CEP: 002220-010
```
"""

print('Nome: Yago Monteiro\nEndereço: Rua ABC\nCEP: 24110-002')

"""03 - Elabore um programa que recebe o nome de uma pessoa do terminal e mostra a seguinte mensagem: `Olá {nome}! Seja bem vindo ao fantástico mundo da programação`"""

nome= input("Insira seu nome: ")
print(f'Olá {nome}! Seja bem vindo ao fantástico mundo da programação')

"""# **Operadores: Aritméticos, Relacionais e Lógicos**

## Operadores Aritméticos

Simbolo   | Significado
--------- | ---------
+ | Adição
- | Subtração
* | Multiplicação
/ | Divisão
// | Divisão inteira
** | Exponenciação
% | Resto da divisão(mod)

Agora vamos solicitar um valor para o user, para realizarmos todas essas operações, porém precisamos converter o valor do input como vimos anteriormente:
"""

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))

soma = n1 + n2
sub = n1 - n2
mult = n1 * n2
div = n1 / n2
divInteira = n1 // n2
expo = n1 ** n2
mod = n1 % n2

print(f'{n1} + {n2} = {soma}')
print(f'{n1} - {n2} = {sub}')
print(f'{n1} * {n2} = {mult}')
print(f'{n1} / {n2} = {div}')
print(f'{n1} // {n2} = {divInteira}')
print(f'{n1} ** {n2} = {expo}')
print(f'{n1} % {n2} = {mod}')

"""Para limitar as casas decimais de uma var float precisamos aplicar essa formatação:"""

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))

div = n1 / n2

print(f'{n1} / {n2} = {div:.2f}') # 2f é a quantidade de casas decimais desejadas.

"""## Operadores Aritméticos

Simbolo   | Significado
--------- | ---------
> | Maior que
< | Menor que
>= | Maior OU igual que
<= | Menor OU igual que
!= | Diferente de
== | Igual a

Caracteristicas desses operadores:

* Sempre retornam True ou False
* São usados para comparar valores
* Utilize a técnica de perguntar


"""

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))

print(f'{n1} é maior que {n2}? {n1 > n2}')
print(f'{n1} é menor que {n2}? {n1 < n2}')
print(f'{n1} é maior ou igual que {n2}? {n1 >= n2}')
print(f'{n1} é menor ou igual que {n2}? {n1 <= n2}')
print(f'{n1} é diferente de {n2}? {n1 != n2}')
print(f'{n1} é igual a {n2}? {n1 == n2}')

"""## Operadores Lógicos

* and (E)
* or  (OU)
* not (Negação)

Retorna True ou False e compara duas expreções relacionais:
"""

n1 = 1
n2 = 2
n3 = 3
n4 = 4

# Vamos perguntar: n1 é maior que n2 E n3 é menor que n4?
# A resposta só será True se TODAS as relações forem True:

print(n1 > n2 and n3 < n4) # Nesse caso da False, por que n1 não é maior que n2

# Vamos perguntar: n1 é maior que n2 OU n3 é menor que n4?
# A resposta será True se ao menos UMA relação for True:

print(n1 > n2 or n3 < n4) # Nesse caso da True, por que pelo menos n3 é menor que n4

# O operador NOT, serve para negar o resultado da operação.
# Ou seja, ele inverte o resultado, se for True, transforma em False e vice versa.

print(not n1 > n2) # Retorna True, por que o resultado de n1 maior que n2 é False

# Para negar uma operação composta de operadores relacionais e lógicos devemos usar as {}:

print(not {n1 > n2 or n3 < n4}) # Aqui retornaria True, se não fosse o not.

"""## Exercicios de operadores

04 - Elabore um programa que recebe dois valores inteiros e mostra a soma desses valores

**Exemplo:**

```
Primeiro Valor = 2
Segundo Valor = 3
Soma = 5
```
"""

v1 = float (input("Insira um número: "))
v2 =  float (input("Insira outro número: "))
soma= v1 + v2
print(f'A soma de {(v1):.2f} + {(v2):.2f} é {(soma):.2f}.')

"""05 - Elabore um programa que receba 4 notas de um aluno e calcule a média dele.

**Exemplo:**

```
Primeiro Nota = 7
Segundo Nota = 8
Terceiro Nota = 10
Quarto Nota = 6

Média = 7,75
```
"""

n1= float (input("Insira a primeira nota: "))
n2= float (input("Insira a segunda nota: "))
n3= float (input("Insira a terceira nota: "))
n4= float (input("Insira a quarta nota: "))

media= (n1 + n2 + n3 + n4)/4
print(f' A média das notas {(n1):.2f}, {(n2):.2f}, {(n3):.2f}, {(n4):.2f} é {(media):.2f}.')

Primeiro Nota = 7
Segundo Nota = 8
Terceiro Nota = 10
Quarto Nota = 6

"""

```
# This is formatted as code
```

06 - Elabore um programa que recebe dois valores inteiros e mostra se o primeiro valor é maior ou igual ao segundo valor

**Exemplo:**
```
Primeiro Valor = 3
Segundo Valor = 2
Resultado = True
```"""

v1= int (input('Insira um número: '))
v2= int (input('Insira outro número: '))

print(f'{v1} é maior ou igual que {v2}: {v1>=v2}')